### PR TITLE
Unit test coverage

### PR DESCRIPTION
**Pull request by ghzlatarev**
closes Manta-Network/Manta#64

* Unit test coverage for manta-asset

### CODE REVIEW

**Comment by ghzlatarev** [comment]
Merge after https://github.com/Manta-Network/Manta/pull/92

**Comment by stechu** [comment]
sorry for didn't review the changes earlier. Since the `serdes` is going to be changed. Maybe it makes sense to merge this after the `serdes` change.

**Comment by ghzlatarev** [comment]
> sorry for didn't review the changes earlier. Since the `serdes` is going to be changed. Maybe it makes sense to merge this after the `serdes` change.

Cool, i'll make the necessary changes here when you merge your pr.

**Comment by ghzlatarev** [comment]
> sorry for didn't review the changes earlier. Since the `serdes` is going to be changed. Maybe it makes sense to merge this after the `serdes` change.

Fixed.

**Review by stechu — APPROVED** [review]

**Pull request merged**
